FROM openjdk:8
RUN curl https://downloads.typesafe.com/play/1.4.4/play-1.4.4.zip --output play.zip \
    && unzip play.zip -d / \
    && rm play.zip \
    && chmod a+x /play/play
ENV PATH $PATH:/play
