FROM openjdk:8
ARG v=1.4.4
RUN curl https://downloads.typesafe.com/play/$v/play-$v.zip --output play.zip \
    && unzip play.zip -d / \
    && rm play.zip \
    && mv play-$v play \
    && chmod a+x /play/play \
    && wget http://mirror.linux-ia64.org/apache//ant/binaries/apache-ant-1.10.5-bin.zip \
    && unzip apache-ant-1.10.5-bin.zip \
    && rm apache-ant-1.10.5-bin.zip \
    && mv apache-ant-1.10.5 /ant \
ENV PATH $PATH:/play
ENV ANT_HOME /ant
ENV PATH $PATH:$ANT_HOME/bin
